url: https://gamejam.dulwich.org/
baseurl: /

# Site settings
title: Dulwich Game Jam 2023
email: jared.rigby@dulwich.org
description: "Dulwich Game Jam 2023 - create awesome games, win awesome prizes!"


# Team names, titles and social links
people:
- name: Dr Yufeng Chi
  pic: yufeng
  position: Founder of Perfect World Games
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Colin Walder
  pic: colin
  position: Engineering Director at CD PROJEKT RED
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #

- name: Dr Alena Denisova
  pic: alena
  position: Video Game Researcher and Lecturer of Computer Science
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: google-plus
  #    url: #

- name: Dr Sean Walton
  pic: sean
  position: Indie Studio Owner and Lecturer of Computer Science

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty