url: https://gamejam.dulwich.org

# Site settings
title: Dulwich Game Jam 2023
email: jared.rigby@dulwich.org
description: "Dulwich Game Jam 2023 - create awesome games, win awesome prizes!"


# Team names, titles and social links
people:
- name: 育碧游戏
  pic: ubisoft
  position: Ubisoft China

- name: Mr Colin Walder
  pic: colin
  position: CD PROJEKT RED

- name: Dr Alena Denisova
  pic: alena
  position: The University of York

- name: Dr Sean Walton
  pic: sean
  position: Swansea University

Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 - title: facebook
   url: https://www.facebook.com/EiM.Education.in.Motion
 - title: linkedin
   url: https://www.linkedin.com/company/educationinmotion/

# Postal address (add as many lines as necessary)
address:
  - line: Dulwich College Beijing
  - line: 89 Capital Airport Road
  - line: Shunyi District
  - line: Beijing
  - line: China

# Build settings
markdown: kramdown
permalink: pretty

collections:
  games:
    output: false